name: "Simple Test Schedule"

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test step
        run: |
          echo "Test executed at: $(date)"
          echo "Current time UTC: $(date -u)"
